// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GuavaRedisHbase.proto

package com.GuavaRedisHbase;

public final class RedisHbasePro {
  private RedisHbasePro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface getValueRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getValueRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string rowKey = 1;</code>
     */
    boolean hasRowKey();
    /**
     * <code>required string rowKey = 1;</code>
     */
    java.lang.String getRowKey();
    /**
     * <code>required string rowKey = 1;</code>
     */
    com.google.protobuf.ByteString
        getRowKeyBytes();

    /**
     * <code>required string family = 2;</code>
     */
    boolean hasFamily();
    /**
     * <code>required string family = 2;</code>
     */
    java.lang.String getFamily();
    /**
     * <code>required string family = 2;</code>
     */
    com.google.protobuf.ByteString
        getFamilyBytes();

    /**
     * <code>required string column = 3;</code>
     */
    boolean hasColumn();
    /**
     * <code>required string column = 3;</code>
     */
    java.lang.String getColumn();
    /**
     * <code>required string column = 3;</code>
     */
    com.google.protobuf.ByteString
        getColumnBytes();
  }
  /**
   * Protobuf type {@code getValueRequest}
   */
  public static final class getValueRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:getValueRequest)
      getValueRequestOrBuilder {
    // Use getValueRequest.newBuilder() to construct.
    private getValueRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private getValueRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final getValueRequest defaultInstance;
    public static getValueRequest getDefaultInstance() {
      return defaultInstance;
    }

    public getValueRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private getValueRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              rowKey_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              family_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              column_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.GuavaRedisHbase.RedisHbasePro.internal_static_getValueRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.GuavaRedisHbase.RedisHbasePro.internal_static_getValueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.GuavaRedisHbase.RedisHbasePro.getValueRequest.class, com.GuavaRedisHbase.RedisHbasePro.getValueRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<getValueRequest> PARSER =
        new com.google.protobuf.AbstractParser<getValueRequest>() {
      public getValueRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getValueRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<getValueRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ROWKEY_FIELD_NUMBER = 1;
    private java.lang.Object rowKey_;
    /**
     * <code>required string rowKey = 1;</code>
     */
    public boolean hasRowKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string rowKey = 1;</code>
     */
    public java.lang.String getRowKey() {
      java.lang.Object ref = rowKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rowKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rowKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRowKeyBytes() {
      java.lang.Object ref = rowKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rowKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAMILY_FIELD_NUMBER = 2;
    private java.lang.Object family_;
    /**
     * <code>required string family = 2;</code>
     */
    public boolean hasFamily() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string family = 2;</code>
     */
    public java.lang.String getFamily() {
      java.lang.Object ref = family_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          family_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string family = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      java.lang.Object ref = family_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMN_FIELD_NUMBER = 3;
    private java.lang.Object column_;
    /**
     * <code>required string column = 3;</code>
     */
    public boolean hasColumn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string column = 3;</code>
     */
    public java.lang.String getColumn() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          column_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string column = 3;</code>
     */
    public com.google.protobuf.ByteString
        getColumnBytes() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        column_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rowKey_ = "";
      family_ = "";
      column_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRowKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFamily()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRowKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getColumnBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRowKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getColumnBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getValueRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.GuavaRedisHbase.RedisHbasePro.getValueRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getValueRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getValueRequest)
        com.GuavaRedisHbase.RedisHbasePro.getValueRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.GuavaRedisHbase.RedisHbasePro.internal_static_getValueRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.GuavaRedisHbase.RedisHbasePro.internal_static_getValueRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.GuavaRedisHbase.RedisHbasePro.getValueRequest.class, com.GuavaRedisHbase.RedisHbasePro.getValueRequest.Builder.class);
      }

      // Construct using com.GuavaRedisHbase.RedisHbasePro.getValueRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        family_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        column_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.GuavaRedisHbase.RedisHbasePro.internal_static_getValueRequest_descriptor;
      }

      public com.GuavaRedisHbase.RedisHbasePro.getValueRequest getDefaultInstanceForType() {
        return com.GuavaRedisHbase.RedisHbasePro.getValueRequest.getDefaultInstance();
      }

      public com.GuavaRedisHbase.RedisHbasePro.getValueRequest build() {
        com.GuavaRedisHbase.RedisHbasePro.getValueRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.GuavaRedisHbase.RedisHbasePro.getValueRequest buildPartial() {
        com.GuavaRedisHbase.RedisHbasePro.getValueRequest result = new com.GuavaRedisHbase.RedisHbasePro.getValueRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowKey_ = rowKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.family_ = family_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.column_ = column_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.GuavaRedisHbase.RedisHbasePro.getValueRequest) {
          return mergeFrom((com.GuavaRedisHbase.RedisHbasePro.getValueRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.GuavaRedisHbase.RedisHbasePro.getValueRequest other) {
        if (other == com.GuavaRedisHbase.RedisHbasePro.getValueRequest.getDefaultInstance()) return this;
        if (other.hasRowKey()) {
          bitField0_ |= 0x00000001;
          rowKey_ = other.rowKey_;
          onChanged();
        }
        if (other.hasFamily()) {
          bitField0_ |= 0x00000002;
          family_ = other.family_;
          onChanged();
        }
        if (other.hasColumn()) {
          bitField0_ |= 0x00000004;
          column_ = other.column_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRowKey()) {
          
          return false;
        }
        if (!hasFamily()) {
          
          return false;
        }
        if (!hasColumn()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.GuavaRedisHbase.RedisHbasePro.getValueRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.GuavaRedisHbase.RedisHbasePro.getValueRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object rowKey_ = "";
      /**
       * <code>required string rowKey = 1;</code>
       */
      public boolean hasRowKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string rowKey = 1;</code>
       */
      public java.lang.String getRowKey() {
        java.lang.Object ref = rowKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            rowKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rowKey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRowKeyBytes() {
        java.lang.Object ref = rowKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rowKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rowKey = 1;</code>
       */
      public Builder setRowKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rowKey = 1;</code>
       */
      public Builder clearRowKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowKey_ = getDefaultInstance().getRowKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string rowKey = 1;</code>
       */
      public Builder setRowKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object family_ = "";
      /**
       * <code>required string family = 2;</code>
       */
      public boolean hasFamily() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string family = 2;</code>
       */
      public java.lang.String getFamily() {
        java.lang.Object ref = family_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            family_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string family = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFamilyBytes() {
        java.lang.Object ref = family_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          family_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string family = 2;</code>
       */
      public Builder setFamily(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        family_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 2;</code>
       */
      public Builder clearFamily() {
        bitField0_ = (bitField0_ & ~0x00000002);
        family_ = getDefaultInstance().getFamily();
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 2;</code>
       */
      public Builder setFamilyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        family_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object column_ = "";
      /**
       * <code>required string column = 3;</code>
       */
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string column = 3;</code>
       */
      public java.lang.String getColumn() {
        java.lang.Object ref = column_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            column_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string column = 3;</code>
       */
      public com.google.protobuf.ByteString
          getColumnBytes() {
        java.lang.Object ref = column_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          column_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string column = 3;</code>
       */
      public Builder setColumn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 3;</code>
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 3;</code>
       */
      public Builder setColumnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        column_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:getValueRequest)
    }

    static {
      defaultInstance = new getValueRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:getValueRequest)
  }

  public interface getBackResultResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getBackResultResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string BackResult = 1;</code>
     */
    boolean hasBackResult();
    /**
     * <code>required string BackResult = 1;</code>
     */
    java.lang.String getBackResult();
    /**
     * <code>required string BackResult = 1;</code>
     */
    com.google.protobuf.ByteString
        getBackResultBytes();
  }
  /**
   * Protobuf type {@code getBackResultResponse}
   */
  public static final class getBackResultResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:getBackResultResponse)
      getBackResultResponseOrBuilder {
    // Use getBackResultResponse.newBuilder() to construct.
    private getBackResultResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private getBackResultResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final getBackResultResponse defaultInstance;
    public static getBackResultResponse getDefaultInstance() {
      return defaultInstance;
    }

    public getBackResultResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private getBackResultResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              backResult_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.GuavaRedisHbase.RedisHbasePro.internal_static_getBackResultResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.GuavaRedisHbase.RedisHbasePro.internal_static_getBackResultResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.class, com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<getBackResultResponse> PARSER =
        new com.google.protobuf.AbstractParser<getBackResultResponse>() {
      public getBackResultResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getBackResultResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<getBackResultResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BACKRESULT_FIELD_NUMBER = 1;
    private java.lang.Object backResult_;
    /**
     * <code>required string BackResult = 1;</code>
     */
    public boolean hasBackResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string BackResult = 1;</code>
     */
    public java.lang.String getBackResult() {
      java.lang.Object ref = backResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          backResult_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string BackResult = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBackResultBytes() {
      java.lang.Object ref = backResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      backResult_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBackResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBackResultBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBackResultBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getBackResultResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getBackResultResponse)
        com.GuavaRedisHbase.RedisHbasePro.getBackResultResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.GuavaRedisHbase.RedisHbasePro.internal_static_getBackResultResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.GuavaRedisHbase.RedisHbasePro.internal_static_getBackResultResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.class, com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.Builder.class);
      }

      // Construct using com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        backResult_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.GuavaRedisHbase.RedisHbasePro.internal_static_getBackResultResponse_descriptor;
      }

      public com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse getDefaultInstanceForType() {
        return com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.getDefaultInstance();
      }

      public com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse build() {
        com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse buildPartial() {
        com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse result = new com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.backResult_ = backResult_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse) {
          return mergeFrom((com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse other) {
        if (other == com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.getDefaultInstance()) return this;
        if (other.hasBackResult()) {
          bitField0_ |= 0x00000001;
          backResult_ = other.backResult_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBackResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object backResult_ = "";
      /**
       * <code>required string BackResult = 1;</code>
       */
      public boolean hasBackResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string BackResult = 1;</code>
       */
      public java.lang.String getBackResult() {
        java.lang.Object ref = backResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            backResult_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string BackResult = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBackResultBytes() {
        java.lang.Object ref = backResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          backResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string BackResult = 1;</code>
       */
      public Builder setBackResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        backResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string BackResult = 1;</code>
       */
      public Builder clearBackResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        backResult_ = getDefaultInstance().getBackResult();
        onChanged();
        return this;
      }
      /**
       * <code>required string BackResult = 1;</code>
       */
      public Builder setBackResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        backResult_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:getBackResultResponse)
    }

    static {
      defaultInstance = new getBackResultResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:getBackResultResponse)
  }

  /**
   * Protobuf service {@code RedisHbaseProService}
   */
  public static abstract class RedisHbaseProService
      implements com.google.protobuf.Service {
    protected RedisHbaseProService() {}

    public interface Interface {
      /**
       * <code>rpc getVauleFromCo(.getValueRequest) returns (.getBackResultResponse);</code>
       */
      public abstract void getVauleFromCo(
          com.google.protobuf.RpcController controller,
          com.GuavaRedisHbase.RedisHbasePro.getValueRequest request,
          com.google.protobuf.RpcCallback<com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new RedisHbaseProService() {
        @java.lang.Override
        public  void getVauleFromCo(
            com.google.protobuf.RpcController controller,
            com.GuavaRedisHbase.RedisHbasePro.getValueRequest request,
            com.google.protobuf.RpcCallback<com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse> done) {
          impl.getVauleFromCo(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getVauleFromCo(controller, (com.GuavaRedisHbase.RedisHbasePro.getValueRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.GuavaRedisHbase.RedisHbasePro.getValueRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getVauleFromCo(.getValueRequest) returns (.getBackResultResponse);</code>
     */
    public abstract void getVauleFromCo(
        com.google.protobuf.RpcController controller,
        com.GuavaRedisHbase.RedisHbasePro.getValueRequest request,
        com.google.protobuf.RpcCallback<com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.GuavaRedisHbase.RedisHbasePro.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getVauleFromCo(controller, (com.GuavaRedisHbase.RedisHbasePro.getValueRequest)request,
            com.google.protobuf.RpcUtil.<com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.GuavaRedisHbase.RedisHbasePro.getValueRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.GuavaRedisHbase.RedisHbasePro.RedisHbaseProService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getVauleFromCo(
          com.google.protobuf.RpcController controller,
          com.GuavaRedisHbase.RedisHbasePro.getValueRequest request,
          com.google.protobuf.RpcCallback<com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.class,
            com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse getVauleFromCo(
          com.google.protobuf.RpcController controller,
          com.GuavaRedisHbase.RedisHbasePro.getValueRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse getVauleFromCo(
          com.google.protobuf.RpcController controller,
          com.GuavaRedisHbase.RedisHbasePro.getValueRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.GuavaRedisHbase.RedisHbasePro.getBackResultResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:RedisHbaseProService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getValueRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_getValueRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getBackResultResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_getBackResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025GuavaRedisHbase.proto\"A\n\017getValueReque" +
      "st\022\016\n\006rowKey\030\001 \002(\t\022\016\n\006family\030\002 \002(\t\022\016\n\006co" +
      "lumn\030\003 \002(\t\"+\n\025getBackResultResponse\022\022\n\nB" +
      "ackResult\030\001 \002(\t2R\n\024RedisHbaseProService\022" +
      ":\n\016getVauleFromCo\022\020.getValueRequest\032\026.ge" +
      "tBackResultResponseB)\n\023com.GuavaRedisHba" +
      "seB\rRedisHbaseProH\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_getValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_getValueRequest_descriptor,
        new java.lang.String[] { "RowKey", "Family", "Column", });
    internal_static_getBackResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_getBackResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_getBackResultResponse_descriptor,
        new java.lang.String[] { "BackResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
